name: Checks

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: warp-ubuntu-latest-x64-16x
    env:
      # Set features for the Makefile
      FEATURES: ${{ matrix.features }}
    strategy:
      matrix:
        toolchain:
          - stable
        features:
          - ""
          - "redact_sensitive"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      # https://github.com/dtolnay/rust-toolchain
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}

      # https://github.com/swatinem/rust-cache
      - name: Run Swatinem/rust-cache@v2
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      # https://github.com/Mozilla-Actions/sccache-action
      - name: Run sccache-action
        uses: mozilla-actions/sccache-action@v0.0.5

      - name: Set sccache env vars
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Install Foundry toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install native dependencies
        run: sudo apt-get install -y libsqlite3-dev

      - name: Lint
        run: make lint

      - name: Test
        run: make test

  integration:
    name: Integration tests
    runs-on: warp-ubuntu-latest-x64-16x
    needs: lint_and_test
    strategy:
      matrix:
        toolchain:
          - stable
        features:
          - ""
          - "redact_sensitive"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Download builder playground
        uses: flashbots/flashbots-toolchain@v0.1
        with:
          builder-playground: latest

      # https://github.com/swatinem/rust-cache
      - name: Run Swatinem/rust-cache@v2
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      # https://github.com/Mozilla-Actions/sccache-action
      - name: Run sccache-action
        uses: mozilla-actions/sccache-action@v0.0.5

      - name: Set sccache env vars
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Build the rbuilder
        run: cargo build --features="${{ matrix.features }}"

      - name: Run the playground
        run: builder-playground &

      - name: Run integration tests with flags
        run: cargo test --features="${{ matrix.features }}" --package rbuilder --lib -- integration
        env:
          PLAYGROUND: TRUE

      - name: Aggregate playground logs
        # This steps fails if the test fails early and the playground logs dir has not been created
        if: ${{ failure() }}
        run: |
          mkdir /tmp/playground-logs
          mv $HOME/.playground/devnet/logs /tmp/playground-logs
          mv integration_logs /tmp/playground-logs

      - name: Archive playground logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playground-logs
          path: /tmp/playground-logs
          retention-days: 5
